apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort        # AWS EC2의 특정 포트로 직접 접속
  selector:
    app: backend        # Deployment의 라벨과 일치해야 함
  ports:
    - protocol: TCP
      port: 8080        # 서비스 내부 포트 (ClusterIP용)
      targetPort: 8080  # 파드(Spring Boot)가 실제로 띄운 포트
      nodePort: 31245   # ★ 외부 접속 포트 (30000~32767 사이 지정 가능)
